[phases.setup]
nixPkgs = [
  "nodejs_20",
  "nss",
  "freetype",
  "harfbuzz",
  "dejavu_fonts",
  "glib",
  "libGL",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXcursor",
  "xorg.libXi",
  "cups",
  "dbus",
  "atk",
  "at-spi2-atk",
  "pango",
  "cairo",
  "libdrm",
  "mesa",
  "expat",
  "nspr"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
