[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "dejavu_fonts"
]

[phases.build]
cmds = ["npm install", "which chromium || which chromium-browser || echo 'chromium not found'"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
